// src/routes/404/+page.svelte
<script lang="ts">
    const title = "Error: 404";
</script>

<svelte:head>
    <title>{title} &ndash; SmoothNanners</title>

    <meta name="robots" content="noindex" />
</svelte:head>

<div class="text-white-50">
    <h1>{title}</h1>

    <div class="mb-4">This page could not be found.</div>
</div>

// src/pages/404.tsx
import type { NextPage } from "next";
import HeadWithTitle from "@/components/HeadWithTitle";

const Custom404: NextPage = () => {
    const title = "Page Not Found";

    return (
        <>
            <HeadWithTitle title={title} noIndex />

            <div className="text-white-50">
                <h1>{title}</h1>

                <div>This page could not be found.</div>
            </div>
        </>
    );
};

export default Custom404;
